curso/urls.py
from django.urls import path

from . import views
from .views import (CourseCreateView, CourseDetailView, CourseListView,
                    CourseUpdateView,
                    MatterCreateView, MatterDetailView, MatterListView,
                    MatterUpdateView,
                    StudentDetailView, StudentCreateView)

app_name = 'curso'


urlpatterns = [
    path('', CourseListView.as_view(), name='home'),
    path('course/<int:pk>/', CourseDetailView.as_view(), name='description'),
    path('course/edit/<int:pk>/', CourseUpdateView.as_view(), name='course_edit'),
    path('matter/<int:pk>/', MatterDetailView.as_view(), name='matterDesc'),
    path('matter/edit/<int:pk>/', MatterUpdateView.as_view(), name='matter_edit'),
    path('novocurso/', CourseCreateView.as_view(), name='newCourse'),
    path('novamateria/', MatterCreateView.as_view(), name='nova_materia'),
    path('novoestudante/', StudentCreateView.as_view(), name='novo_estudante'),
    path('student/<int:pk>/', StudentDetailView.as_view(), name='student_desc'),
]

# como colocar uma url atrás da outra?

cursos/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include('curso.urls')),
    path('admin/', admin.site.urls),
]

curso/models.py
from django.db import models

# Create your models here.


class Course(models.Model):
    idCourse = models.AutoField(primary_key=True)
    nameCourse = models.CharField(max_length=45)
    descriptionCourse = models.TextField()

    def __str__(self):
        return self.nameCourse

# E o UUIDField


class Matter(models.Model):
    idMatter = models.AutoField(primary_key=True)
    nameMatter = models.CharField(
        max_length=32,
        help_text='Nome da Matéria')
    descriptionMatter = models.TextField(
        help_text='Uma breve descrição da ementa')
    numberStudent = models.IntegerField(
        help_text='O máximo de alunos por turma')
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    students = models.ManyToManyField('Student', through='StudentHasMatter')

    def __str__(self):
        return self.nameMatter
        # return f'{self.nameMatter} ({self.course})'


class Teacher(models.Model):
    idTeacher = models.AutoField(primary_key=True)
    nameTeacher = models.CharField(
        max_length=64,
        help_text='Nome do Professor')
    matter = models.OneToOneField(
        Matter,
        on_delete=models.CASCADE)
    # Poderia usar models.SET_NULL?

    def __str__(self):
        return self.nameTeacher


class Student(models.Model):
    idStudent = models.AutoField(primary_key=True)
    nameStudent = models.CharField(
        max_length=32,
        help_text='Nome do Aluno')

    def __str__(self):
        return self.nameStudent


class StudentHasMatter(models.Model):
    matter = models.ForeignKey('Matter', on_delete=models.DO_NOTHING)
    student = models.ForeignKey('Student', on_delete=models.DO_NOTHING)
    note = models.DecimalField(max_digits=4, decimal_places=2)

    def __str__(self):
        return f"{self.student}"

curso/forms.py
from django.forms import ModelForm
from .models import Course


class CourseForm(ModelForm):
    class Meta:
        model = Course
        fields = ['nameCourse', 'descriptionCourse']

curso/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView
from django.views.generic.edit import UpdateView

from .forms import CourseForm
from .models import Course, Matter, Student

# Create your views here.


class CourseCreateView(CreateView):
    model = Course
    success_url = reverse_lazy('curso:home')
    form_class = CourseForm


class CourseListView(ListView):
    model = Course


class CourseDetailView(DetailView):
    model = Course


class CourseUpdateView(UpdateView):
    model = Course
    fields = '__all__'
    success_url = reverse_lazy('curso:home')


class MatterCreateView(CreateView):
    model = Matter
    success_url = reverse_lazy('curso:home')
    fields = '__all__'


class MatterListView(ListView):
    model = Matter


class MatterDetailView(DetailView):
    model = Matter


class MatterUpdateView(UpdateView):
    model = Matter
    success_url = reverse_lazy('curso:home')
    fields = '__all__'


class StudentCreateView(CreateView):
    model = Student
    success_url = reverse_lazy('curso:home')
    fields = '__all__'


class StudentDetailView(DetailView):
    model = Student


# def home(request):
#     college = Course.objects.all().order_by('nameCourse')
#     context = {'allCourses': college}
#     return render(request, 'curso/course.html', context)


def description(request, courseId):
    try:
        detailCourse = Course.objects.get(idCourse=courseId)
        mattersCourse = detailCourse.matter_set.all().order_by('nameMatter')
    except Course.DoesNotExist:
        raise Http404("Nenhum curso foi encontrado com esse Id")

    context = {'details': detailCourse, 'matters': mattersCourse}
    return render(request, 'curso/detailsCourse.html', context)


def matterDesc(request, matterId):
    matter = Matter.objects.get(idMatter=matterId)
    studentMatter = matter.studenthasmatter_set.all()

    context = {'students': studentMatter, 'matter': matter}
    return render(request, 'curso/detailsMatter.html', context)


# def StudentDesc(request, studentId):
#    pass


# def new_course(request):
#     data = {}
#     form = CourseForm(request.POST or None)

#     if form.is_valid():
#         form.save()
#         return redirect('curso:home')

#     data['form'] = form
#     return render(request, 'curso/newcourse.html', data)

curso/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>Universidade</title>
</head>
<body>
    <div class="container">
        {% block content %} 
                            
        {% endblock %}
    </div>
</body>
</html>

curso/templates/course.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Universidade</title>
</head>
<body>
    <h1>Cursos</h1>
    <ul>
        {% for course in allCourses  %}
            <li>
                <a href="{% url 'curso:description' course.idCourse %}">
                    {{ course }}
                </a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

curso/templates/curso.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Cursos</h1>
    <ul>
        {% for course in allCourses  %}
            <li>{{course}}</li>
        {% endfor %}
    </ul>
</body>
</html>

curso/templates/curso/course.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Universidade</title>
</head>
<body>
    <h1>Cursos</h1>
    <ul>
        {% for course in allCourses  %}
            <li>
                <a href="{% url 'curso:description' course.idCourse %}">
                    {{ course }}
                </a>
            </li>
        {% endfor %}
    </ul>

    <a href="{% url 'curso:newCourse'%}">Novo Curso</a>
</body>
</html>

curso/templates/curso/course_detail.html
{% extends '../base.html' %}

{% block content%}
    <h1>{{object}}</h1>
    <p>
        Ementa: {{ object.descriptionCourse }}
        
    </p>
        {% for matter in object.matter_set.all%}
            <p>
                <a href="{%url 'curso:matterDesc' matter.idMatter%}">{{matter}}</a>
            </p>
        {%endfor%}
    <a href="{% url 'curso:course_edit' object.pk%}">Editar</a>

{%endblock%}

curso/templates/curso/course_form.html
{% extends '../base.html' %}

{% block content%}
    <h1>Novo Curso</h1>

    <form method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Salvar</button>
    </form>
{% endblock %}

curso/templates/curso/course_list.html
{% extends '../base.html' %}

{% block content%}

    <h1 class="display-3">
        Cursos
    </h1>
    <div class="row">
        <div class="col">
            <p>
                <a href="{% url 'curso:newCourse'%}">Novo Curso</a>
            </p>
            <p>
                <a href="{% url 'curso:nova_materia'%}">Nova Matéria</a>
            </p>
            <p>
                <a href="{% url 'curso:novo_estudante'%}">Novo Estudante</a>
            </p>
        </div>    
        <div class="col">
            <ul>
                {% for course in object_list  %}
                    <div class="col">
                        <li>
                            <a href="{% url 'curso:description' course.idCourse %}">
                                {{ course }}
                            </a>
                        </li>
                    </div>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

curso/templates/curso/course_update_form.html
{% extends '../base.html' %}

{% block content%}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}

curso/templates/curso/detailsMatter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        Detalhes da matéria
    </title>
</head>
<body>
    <h3>{{ matter }}</h3>
    <ul>
        <p>Alunos</p>
        {% for allStudents in students %}
            <li>
                {{ allStudents }}
            </li>
        {% endfor %}    
    </ul>
</body>
</html>

curso/templates/curso/detailsStudent.html
{% extends '../base.html' %}

{% block content%}
    <h1 class="display-3">Alunos</h1>
{%endblock%}

curso/templates/curso/matter_detail.html
{% extends '../base.html' %}

{% block content%}
    <h3>{{ object }}</h3>
    <ul>
        <p>Professor: {{object.teacher}}</p>
        <p>Alunos</p>
        {% for students in object.students.all %}
            <li>
                {{ students }}
            </li>
        {% endfor %}    
    </ul>
    <a href="{% url 'curso:matter_edit' object.pk%}">Editar</a>
{%endblock%}

curso/templates/curso/matter_form.html
{% extends '../base.html' %}

{% block content%}
    <h1>Nova Matéria</h1>

    <form method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Salvar</button>
    </form>

{% endblock %}

curso/templates/curso/matter_update_form.html
{% extends '../base.html' %}

{% block content%}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}

curso/templates/curso/newcourse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Novo Curso</h1>

    <form method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Salvar</button>
    </form>
</body>
</html>

curso/templates/curso/student_detail.html
{% extends '../base.html' %}

{% block content%}
    <h1 class="display-3">Alunos</h1>
    <p>{{object.idStudent}}
    {{object.nameStudent}}</p>
{%endblock%}

curso/templates/curso/student_form.html
{% extends '../base.html' %}

{% block content%}
    <h1>Novo Estudante</h1>

    <form method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Salvar</button>
    </form>
{%endblock%}

curso/templates/detailsCourse.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Detalhes do Curso</title>
</head>
    <body>
        <h1>{{ details }}</h1>
        <b><h3>Descrição:</h3></b> 
            {{ details.descriptionCourse }}
        <b><h3>Matérias:</h3></b>  
            <ul>
                {% for allMatters in matters %}
                <li>
                    <a href="{% url 'curso:matterDesc' allMatters.idMatter %}">
                        {{allMatters}}
                    </a>
                </li>
                    <p>{{allMatters.descriptionMatter}}</p>
                {% endfor %}
            </ul>
        </body>
</html>

curso/templates/detailsMatter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Detalhes da matéria
    </title>
</head>
<body>
    <h3>{{ matter }}</h3>
    <ul>
        {% for allStudents in students %}
            <li>{{ allStudents }}</li>
        {% endfor %}
    </ul>
</body>
</html>